version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - web

networks:
  web:
