version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - web

networks:
  web:
