version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - web

networks:
  web:
